- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc-setup
    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpc_out
  # - debug:
  #      var: vpc_out
    - name: Create Pub Sub1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: PubSub1
      register: pubsub1_out
    - name: Create Pub Sub2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{pubsub2}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: PubSub2
      register: pubsub2_out
    - name: Create Priv Sub1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{privsub1}}"
        state: "{{state}}"
        resource_tags:
          Name: Privsub1
      register: privsub1_out
    - name: Create Priv Sub2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{privsub2}}"
        state: "{{state}}"
        resource_tags:
          Name: PrivSub2
      register: privsub2_out
    - name: Create IGW for Subnets network
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: Project-IGW
      register: igw_out
    - name: Create Pub RT For Pub Sub
      ec2_vpc_route_table:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: public RT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
        register: public_rt_out













