- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc-setup
    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpc_out
  # - debug:
  #      var: vpc_out
    - name: Create Pub Sub1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: PubSub1
      register: pubsub1_out







